#!/bin/bash

GPU_IDS="3,4"

docker run --rm --runtime=nvidia \
  --name="class-cgiacchetta-rsde-2" \
  -e CUDA_VISIBLE_DEVICES=$GPU_IDS \
  --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
  -t -u $(id -u):$(id -g) \
  -v $(pwd):$(pwd) -w $(pwd) \
  class-cgiacchetta-rsde2:latest